export const COMPANIES = [
  { id: 'c1', name: 'Wexa AI', industry: 'Applied AI & Agents', size: '25-50', location: 'San Francisco, CA' },
  { id: 'c2', name: 'CognoDB', industry: 'Graph Database & Storage Engines', size: '50-100', location: 'New York, NY' },
  { id: 'c3', name: 'Stripe', industry: 'Fintech & Payments Infrastructure', size: '5000+', location: 'San Francisco, CA' },
  { id: 'c4', name: 'Vercel', industry: 'Developer Tools & Cloud', size: '500-1000', location: 'Remote / Global' },
  { id: 'c5', name: 'Anthropic', industry: 'AI Safety & Foundation Models', size: '200-500', location: 'San Francisco, CA' },
  { id: 'c6', name: 'Datadog', industry: 'Observability & Monitoring', size: '2000-5000', location: 'Boston, MA' },
  { id: 'c7', name: 'Figma', industry: 'Design Systems & Collaboration', size: '1000-2000', location: 'San Francisco, CA' },
  { id: 'c8', name: 'Supabase', industry: 'Open Source Backend & DBs', size: '100-250', location: 'Remote / Global' },
  { id: 'c9', name: 'Linear', industry: 'Productivity & Issue Tracking', size: '50-100', location: 'San Francisco, CA' },
  { id: 'c10', name: 'Scale AI', industry: 'Data Engine & RLHF', size: '500-1000', location: 'San Francisco, CA' },
  { id: 'c11', name: 'Mistral AI', industry: 'Open-Weight LLMs', size: '50-100', location: 'Paris, France' },
  { id: 'c12', name: 'Neo4j Labs', industry: 'Graph Platform', size: '500-1000', location: 'Malmö, Sweden' },
];

export const SKILLS = [
  // AI & ML
  { id: 's1', name: 'LLM Fine-tuning', category: 'AI & ML' },
  { id: 's2', name: 'RAG Architecture', category: 'AI & ML' },
  { id: 's3', name: 'PyTorch', category: 'AI & ML' },
  { id: 's4', name: 'LangChain & LlamaIndex', category: 'AI & ML' },
  { id: 's5', name: 'Vector Embeddings', category: 'AI & ML' },
  
  // Data & Graph
  { id: 's6', name: 'Cypher & Graph DBs', category: 'Data & Graph' },
  { id: 's7', name: 'Neo4j / CognoDB', category: 'Data & Graph' },
  { id: 's8', name: 'Knowledge Graphs', category: 'Data & Graph' },
  { id: 's9', name: 'PostgreSQL & pgvector', category: 'Data & Graph' },
  { id: 's10', name: 'Distributed Systems', category: 'Data & Graph' },

  // Frontend & UI
  { id: 's11', name: 'React & Next.js', category: 'Frontend' },
  { id: 's12', name: 'TypeScript & JavaScript', category: 'Frontend' },
  { id: 's13', name: 'Tailwind CSS', category: 'Frontend' },
  { id: 's14', name: 'WebSockets & Realtime', category: 'Frontend' },
  { id: 's15', name: 'Canvas & D3 / Graph Viz', category: 'Frontend' },

  // Backend & Cloud
  { id: 's16', name: 'Node.js & Express', category: 'Backend' },
  { id: 's17', name: 'Go / Golang', category: 'Backend' },
  { id: 's18', name: 'Rust', category: 'Backend' },
  { id: 's19', name: 'Kubernetes & Docker', category: 'Cloud & Infra' },
  { id: 's20', name: 'GraphQL & gRPC', category: 'Backend' },
  { id: 's21', name: 'AWS & Cloud Architecture', category: 'Cloud & Infra' },

  // Product & Design
  { id: 's22', name: 'Product Management', category: 'Product & Mobile' },
  { id: 's23', name: 'Design Systems', category: 'Design & UX' },
  { id: 's24', name: 'Mobile (React Native / iOS)', category: 'Product & Mobile' },
];

export const PROJECTS = [
  {
    id: 'pr1',
    name: 'Autonomous Agent Orchestration Engine',
    summary: 'A multi-agent graph planner enabling cooperative LLM workflows with deterministic memory.',
    status: 'Active',
    companyId: 'c1',
    requiredSkills: ['LLM Fine-tuning', 'RAG Architecture', 'Cypher & Graph DBs', 'Python / PyTorch', 'Node.js & Express'],
  },
  {
    id: 'pr2',
    name: 'Sub-Millisecond Graph Storage Engine',
    summary: 'Custom LSM-tree pointer graph storage engine engineered for deep 6-hop traversals.',
    status: 'Active',
    companyId: 'c2',
    requiredSkills: ['Cypher & Graph DBs', 'Distributed Systems', 'Rust', 'Go / Golang'],
  },
  {
    id: 'pr3',
    name: 'Global Real-time Payments Ledger',
    summary: 'High-throughput idempotent transactional system handling 50k+ authorizations/sec.',
    status: 'Completed',
    companyId: 'c3',
    requiredSkills: ['Distributed Systems', 'PostgreSQL & pgvector', 'Node.js & Express', 'Go / Golang'],
  },
  {
    id: 'pr4',
    name: 'Next-Gen Edge Runtime & AI Streaming',
    summary: 'Zero-cold-start edge compute layer for streaming token generation and web hydration.',
    status: 'Active',
    companyId: 'c4',
    requiredSkills: ['React & Next.js', 'TypeScript & JavaScript', 'WebSockets & Realtime', 'Rust'],
  },
  {
    id: 'pr5',
    name: 'Constitutional Alignment & RLHF Benchmark',
    summary: 'Automated evaluation framework for synthetic prompt testing and red-teaming.',
    status: 'Active',
    companyId: 'c5',
    requiredSkills: ['PyTorch', 'LLM Fine-tuning', 'Vector Embeddings', 'Knowledge Graphs'],
  },
  {
    id: 'pr6',
    name: 'Unified Graph Observability Canvas',
    summary: 'Interactive network topology visualizer mapping service mesh dependency chains.',
    status: 'Beta',
    companyId: 'c6',
    requiredSkills: ['Canvas & D3 / Graph Viz', 'React & Next.js', 'Cypher & Graph DBs', 'GraphQL & gRPC'],
  },
];

export const ANCHOR_PEOPLE = [
  {
    id: 'p1',
    name: 'Elena Rostova',
    email: 'elena.rostova@wexa.ai',
    title: 'Lead AI & Graph Architect',
    bio: 'Pioneering graph-augmented RAG systems and autonomous agent knowledge graphs. Former research lead at OpenAI.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    experienceYears: 10,
    companyId: 'c1',
    companyRole: 'Founding Architect',
    companySince: '2023',
    skills: [
      { name: 'LLM Fine-tuning', level: 5, years: 6 },
      { name: 'RAG Architecture', level: 5, years: 5 },
      { name: 'Cypher & Graph DBs', level: 5, years: 8 },
      { name: 'Knowledge Graphs', level: 5, years: 8 },
      { name: 'PyTorch', level: 4, years: 7 },
      { name: 'React & Next.js', level: 4, years: 6 },
    ],
    projectIds: ['pr1', 'pr2'],
    mentees: ['p4', 'p8', 'p15'],
  },
  {
    id: 'p2',
    name: 'Marcus Vance',
    email: 'marcus.v@cognodb.com',
    title: 'Principal Distributed Systems Engineer',
    bio: 'Architecting ultra-low latency graph databases and distributed consensus protocols in Rust and C++.',
    location: 'New York, NY',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    experienceYears: 12,
    companyId: 'c2',
    companyRole: 'Head of Core Engine',
    companySince: '2022',
    skills: [
      { name: 'Cypher & Graph DBs', level: 5, years: 10 },
      { name: 'Distributed Systems', level: 5, years: 12 },
      { name: 'Rust', level: 5, years: 7 },
      { name: 'Neo4j / CognoDB', level: 5, years: 9 },
      { name: 'Go / Golang', level: 4, years: 8 },
    ],
    projectIds: ['pr2', 'pr3'],
    mentees: ['p5', 'p12'],
  },
  {
    id: 'p3',
    name: 'Aria Chen',
    email: 'aria.chen@vercel.com',
    title: 'Staff Frontend & Canvas Engineer',
    bio: 'Building hyper-responsive interactive graph canvases, web performance primitives, and edge UI architectures.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    experienceYears: 8,
    companyId: 'c4',
    companyRole: 'Staff Engineer',
    companySince: '2021',
    skills: [
      { name: 'React & Next.js', level: 5, years: 8 },
      { name: 'TypeScript & JavaScript', level: 5, years: 8 },
      { name: 'Canvas & D3 / Graph Viz', level: 5, years: 6 },
      { name: 'Tailwind CSS', level: 5, years: 5 },
      { name: 'WebSockets & Realtime', level: 4, years: 6 },
    ],
    projectIds: ['pr4', 'pr6'],
    mentees: ['p6', 'p11'],
  },
  {
    id: 'p4',
    name: 'Devon Thorne',
    email: 'devon.thorne@wexa.ai',
    title: 'Senior ML & Agent Engineer',
    bio: 'Specializing in agentic tool-use, structured JSON schema outputs, and multi-hop Cypher querying.',
    location: 'Seattle, WA',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    experienceYears: 6,
    companyId: 'c1',
    companyRole: 'Senior Engineer',
    companySince: '2023',
    skills: [
      { name: 'RAG Architecture', level: 4, years: 4 },
      { name: 'LangChain & LlamaIndex', level: 5, years: 4 },
      { name: 'PyTorch', level: 4, years: 5 },
      { name: 'Vector Embeddings', level: 4, years: 4 },
      { name: 'Node.js & Express', level: 4, years: 6 },
    ],
    projectIds: ['pr1'],
    mentorId: 'p1',
  },
  {
    id: 'p5',
    name: 'Tariq Al-Mansoor',
    email: 'tariq@anthropic.com',
    title: 'Staff Alignment Researcher',
    bio: 'Investigating mechanistic interpretability, ontology discovery, and representation engineering in large LLMs.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    experienceYears: 9,
    companyId: 'c5',
    companyRole: 'Research Scientist',
    companySince: '2022',
    skills: [
      { name: 'LLM Fine-tuning', level: 5, years: 6 },
      { name: 'PyTorch', level: 5, years: 8 },
      { name: 'Knowledge Graphs', level: 4, years: 5 },
      { name: 'Vector Embeddings', level: 5, years: 7 },
    ],
    projectIds: ['pr5'],
    mentorId: 'p2',
  },
  {
    id: 'p6',
    name: 'Maya Lin-Kovacs',
    email: 'maya.lin@linear.app',
    title: 'Lead Product Designer & Design Systems',
    bio: 'Crafting high-contrast editorial tools, precision typography hierarchies, and tactile neo-brutalist interaction systems.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    experienceYears: 7,
    companyId: 'c9',
    companyRole: 'Design Lead',
    companySince: '2022',
    skills: [
      { name: 'Design Systems', level: 5, years: 7 },
      { name: 'React & Next.js', level: 4, years: 5 },
      { name: 'Tailwind CSS', level: 5, years: 6 },
      { name: 'Product Management', level: 4, years: 5 },
    ],
    projectIds: ['pr4'],
    mentorId: 'p3',
  },
  {
    id: 'p7',
    name: 'Zane Gallagher',
    email: 'zane.g@datadoghq.com',
    title: 'Principal Observability Architect',
    bio: 'Constructing high-cardinality graph analytics pipelines and dependency topologies across hybrid clouds.',
    location: 'Boston, MA',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
    experienceYears: 11,
    companyId: 'c6',
    companyRole: 'Principal Architect',
    companySince: '2020',
    skills: [
      { name: 'Kubernetes & Docker', level: 5, years: 9 },
      { name: 'Distributed Systems', level: 5, years: 11 },
      { name: 'Go / Golang', level: 5, years: 8 },
      { name: 'Cypher & Graph DBs', level: 4, years: 6 },
      { name: 'GraphQL & gRPC', level: 4, years: 7 },
    ],
    projectIds: ['pr6'],
  },
  {
    id: 'p8',
    name: 'Chloe Davenport',
    email: 'chloe.d@scale.com',
    title: 'Senior RLHF Platform Engineer',
    bio: 'Data engine pipeline design, human feedback loop orchestration, and automated synthetic evaluation.',
    location: 'Austin, TX',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    experienceYears: 5,
    companyId: 'c10',
    companyRole: 'Senior Engineer',
    companySince: '2023',
    skills: [
      { name: 'LLM Fine-tuning', level: 4, years: 4 },
      { name: 'PostgreSQL & pgvector', level: 4, years: 5 },
      { name: 'PyTorch', level: 3, years: 4 },
      { name: 'Node.js & Express', level: 4, years: 5 },
    ],
    projectIds: ['pr5'],
    mentorId: 'p1',
  },
  {
    id: 'p9',
    name: 'Kaito Tanaka',
    email: 'kaito.tanaka@stripe.com',
    title: 'Staff Security & Ledger Engineer',
    bio: 'Zero-trust architecture, cryptographic identity proofs, and distributed Byzantine consensus.',
    location: 'Tokyo, Japan',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    experienceYears: 10,
    companyId: 'c3',
    companyRole: 'Staff Security Engineer',
    companySince: '2019',
    skills: [
      { name: 'Distributed Systems', level: 5, years: 10 },
      { name: 'Rust', level: 4, years: 6 },
      { name: 'Go / Golang', level: 5, years: 8 },
      { name: 'AWS & Cloud Architecture', level: 5, years: 9 },
    ],
    projectIds: ['pr3'],
  },
  {
    id: 'p10',
    name: 'Ananya Sharma',
    email: 'ananya@supabase.com',
    title: 'Head of Developer Experience',
    bio: 'Open source advocate, Postgres extensions, vector indexing, and developer tooling enthusiast.',
    location: 'Toronto, Canada',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    experienceYears: 8,
    companyId: 'c8',
    companyRole: 'Head of DX',
    companySince: '2021',
    skills: [
      { name: 'PostgreSQL & pgvector', level: 5, years: 8 },
      { name: 'TypeScript & JavaScript', level: 5, years: 8 },
      { name: 'React & Next.js', level: 4, years: 7 },
      { name: 'Vector Embeddings', level: 4, years: 4 },
      { name: 'Node.js & Express', level: 5, years: 8 },
    ],
    projectIds: ['pr2', 'pr4'],
  },
  {
    id: 'p11',
    name: 'Lukas Meyer',
    email: 'lukas.m@mistral.ai',
    title: 'Core LLM Systems Engineer',
    bio: 'Quantization, vLLM / SGLang inference serving, and low-bit matrix multiplication kernels.',
    location: 'Paris, France',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    experienceYears: 6,
    companyId: 'c11',
    companyRole: 'Systems Engineer',
    companySince: '2023',
    skills: [
      { name: 'PyTorch', level: 5, years: 6 },
      { name: 'LLM Fine-tuning', level: 4, years: 4 },
      { name: 'Rust', level: 4, years: 5 },
      { name: 'Distributed Systems', level: 4, years: 5 },
    ],
    projectIds: ['pr5'],
    mentorId: 'p5',
  },
  {
    id: 'p12',
    name: 'Siddharth Rao',
    email: 'siddharth.r@cognodb.com',
    title: 'Graph Query Engine Specialist',
    bio: 'Cypher compiler optimization, cost-based graph query planners, and vectorized traversal execution.',
    location: 'New York, NY',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    experienceYears: 7,
    companyId: 'c2',
    companyRole: 'Senior Query Engineer',
    companySince: '2023',
    skills: [
      { name: 'Cypher & Graph DBs', level: 5, years: 7 },
      { name: 'Neo4j / CognoDB', level: 5, years: 7 },
      { name: 'Rust', level: 4, years: 5 },
      { name: 'Knowledge Graphs', level: 4, years: 6 },
    ],
    projectIds: ['pr2'],
    mentorId: 'p2',
  },
  {
    id: 'p13',
    name: 'Sophie Laurent',
    email: 'sophie.laurent@figma.com',
    title: 'Staff Collaboration Engine Engineer',
    bio: 'CRDTs, operational transformation, multi-user real-time canvases, and high-performance WebGL graphics.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    experienceYears: 9,
    companyId: 'c7',
    companyRole: 'Staff Engineer',
    companySince: '2021',
    skills: [
      { name: 'Canvas & D3 / Graph Viz', level: 5, years: 8 },
      { name: 'TypeScript & JavaScript', level: 5, years: 9 },
      { name: 'WebSockets & Realtime', level: 5, years: 7 },
      { name: 'React & Next.js', level: 5, years: 8 },
    ],
    projectIds: ['pr6'],
  },
  {
    id: 'p14',
    name: 'Nicolette Dubois',
    email: 'nicolette@wexa.ai',
    title: 'VP of Product & Strategic Growth',
    bio: 'Scaling AI products from 0 to $20M ARR. Deeply connected in Silicon Valley & European tech ecosystems.',
    location: 'San Francisco, CA',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&auto=format&fit=crop&q=80',
    experienceYears: 13,
    companyId: 'c1',
    companyRole: 'VP Product',
    companySince: '2023',
    skills: [
      { name: 'Product Management', level: 5, years: 12 },
      { name: 'Design Systems', level: 4, years: 6 },
      { name: 'AWS & Cloud Architecture', level: 4, years: 8 },
      { name: 'Knowledge Graphs', level: 3, years: 4 },
    ],
    projectIds: ['pr1'],
  },
  {
    id: 'p15',
    name: 'Jordan Rivera',
    email: 'jordan.rivera@stripe.com',
    title: 'Senior Infrastructure Engineer',
    bio: 'Kubernetes fleet orchestration, cross-region service meshes, and disaster-recovery automation.',
    location: 'Remote, US',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    experienceYears: 7,
    companyId: 'c3',
    companyRole: 'Senior SRE',
    companySince: '2021',
    skills: [
      { name: 'Kubernetes & Docker', level: 5, years: 7 },
      { name: 'AWS & Cloud Architecture', level: 5, years: 7 },
      { name: 'Go / Golang', level: 4, years: 6 },
      { name: 'Distributed Systems', level: 4, years: 6 },
    ],
    projectIds: ['pr3'],
    mentorId: 'p1',
  },
];
